DOWNLINK_BUFFER_TIME = 3

TELEM_DOWNLINK_TIME = 60
    
BOOTUP_SEPARATION_DELAY = 30.0  # seconds

ENTER_LOW_BATTERY_MODE_THRESHOLD = 0.3
EXIT_LOW_BATTERY_MODE_THRESHOLD = 0.5

# TODO Change to +50
ENTER_ECLIPSE_MODE_CURRENT = -50  # mA
ENTER_ECLIPSE_MODE_THRESHOLD = 0.7
LOW_BATT_MODE_SLEEP = 10
IGNORE_LOW_BATTERY = True
    
LOW_CRACKING_PRESSURE = 10.0
HIGH_CRACKING_PRESSURE = 20.0
IDEAL_CRACKING_PRESSURE = 15.0

OPNAV_INTERVAL = 60

GOM_VOLTAGE_MAX = 8400
GOM_VOLTAGE_MIN = 6000

SPLIT_BURNWIRE_DURATION = 1
ANTENNAE_BURNWIRE_DURATION = 1
GLOWPLUG_DURATION = 1

SCHEDULED_BURN_TIME = None

ACS_SPIKE_DURATION = 15  # milliseconds
WANT_TO_ELECTROLYZE = False

DEFAULT_ELECTROLYSIS_DELAY = 1

GYRO_BIAS_X = 0
GYRO_BIAS_Y = 0
GYRO_BIAS_Z = 0

GYRO_BIAS_TEMPERATURE = 0

# TODO
GYRO_BIAS_DXDT = 0
GYRO_BIAS_DYDT = 0
GYRO_BIAS_DZDT = 0
