from fsw.communications.codec import Codec
from fsw.utils.constants import DownlinkKwargs as dk


TIME_codec = Codec(dk.RTC_TIME, "double")
VBOOST_1_codec = Codec(dk.VBOOST_1, "ushort")
VBOOST_2_codec = Codec(dk.VBOOST_2, "ushort")
VBOOST_3_codec = Codec(dk.VBOOST_3, "ushort")
VBATT_codec = Codec(dk.BATTERY_VOLTAGE, "ushort")
CURIN1_codec = Codec(dk.CURRENT_IN_1, "ushort")
CURIN2_codec = Codec(dk.CURRENT_IN_2, "ushort")
CURIN3_codec = Codec(dk.CURRENT_IN_3, "ushort")
CURSUN_codec = Codec(dk.CURSUN, "ushort")
CURSYS_codec = Codec(dk.SYSTEM_CURRENT, "ushort")
RESERVED1_codec = Codec(dk.RESERVED1, "ushort")
CUROUT1_codec = Codec(dk.CUROUT1, "ushort")
CUROUT2_codec = Codec(dk.CUROUT2, "ushort")
CUROUT3_codec = Codec(dk.CUROUT3, "ushort")
CUROUT4_codec = Codec(dk.CUROUT4, "ushort")
CUROUT5_codec = Codec(dk.CUROUT5, "ushort")
CUROUT6_codec = Codec(dk.CUROUT6, "ushort")
OUTPUTS_codec = Codec(dk.OUTPUTS, "ushort")
LATCHUPS1_codec = Codec(dk.LATCHUPS1, "ushort")
LATCHUPS2_codec = Codec(dk.LATCHUPS2, "ushort")
LATCHUPS3_codec = Codec(dk.LATCHUPS3, "ushort")
LATCHUPS4_codec = Codec(dk.LATCHUPS4, "ushort")
LATCHUPS5_codec = Codec(dk.LATCHUPS5, "ushort")
LATCHUPS6_codec = Codec(dk.LATCHUPS6, "ushort")
WDT_TIME_LEFT_I2C_codec = Codec(dk.WDT_TIME_LEFT_I2C, "int")
WDT_TIME_LEFT_GND_codec = Codec(dk.WDT_TIME_LEFT_GND, "int")
WDT_COUNTS_I2C_codec = Codec(dk.WDT_COUNTS_I2C, "int")
WDT_COUNTS_GND_codec = Codec(dk.WDT_COUNTS_GND, "int")
GOM_BOOTS_codec = Codec(dk.GOM_BOOTS, "int")
GOM_BOOTCAUSE_codec = Codec(dk.GOM_BOOTCAUSE, "uint8")
GOM_BATTMODE_codec = Codec(dk.GOM_BATTMODE, "uint8")
# beware integer underflow error
HK_TEMP_1_codec = Codec(dk.HK_TEMP_1, "uint8")
# beware integer underflow error
HK_TEMP_2_codec = Codec(dk.HK_TEMP_2, "uint8")
# beware integer underflow error
HK_TEMP_3_codec = Codec(dk.HK_TEMP_3, "uint8")
# beware integer underflow error
HK_TEMP_4_codec = Codec(dk.HK_TEMP_4, "uint8")
GOM_PPT_MODE_codec = Codec(dk.GOM_PPT_MODE, "uint8")
RESERVED2_codec = Codec(dk.RESERVED2, "ushort")
RTC_TIME_codec = Codec(dk.RTC_TIME, "double")
RPI_CPU_codec = Codec(dk.RPI_CPU, "uint8")
RPI_RAM_codec = Codec(dk.RPI_RAM, "uint8")
RPI_DSK_codec = Codec(dk.RPI_DSK, "uint8")
RPI_TEMP_codec = Codec(dk.RPI_TEMP, "float")
RPI_BOOT_codec = Codec(dk.RPI_BOOT, "double")
RPI_UPTIME_codec = Codec(dk.RPI_UPTIME, "float")
GYROX_codec = Codec(dk.GYROX, "float")
GYROY_codec = Codec(dk.GYROY, "float")
GYROZ_codec = Codec(dk.GYROZ, "float")
ACCX_codec = Codec(dk.ACCX, "float")
ACCY_codec = Codec(dk.ACCY, "float")
ACCZ_codec = Codec(dk.ACCZ, "float")
MAGX_codec = Codec(dk.MAGX, "float")
MAGY_codec = Codec(dk.MAGY, "float")
MAGZ_codec = Codec(dk.MAGZ, "float")
GYRO_TEMP_codec = Codec(dk.GYRO_TEMP, "uint8")
THERMOCOUPLE_TEMP_codec = Codec(dk.THERMOCOUPLE_TEMP, "float")
PROP_TANK_PRESSURE_codec = Codec(dk.PROP_TANK_PRESSURE, "float")
POS_X_codec = Codec(dk.POS_X, "double")
POS_Y_codec = Codec(dk.POS_Y, "double")
POS_Z_codec = Codec(dk.POS_Z, "double")
ATT_1_codec = Codec(dk.ATT_1, "double")
ATT_2_codec = Codec(dk.ATT_2, "double")
ATT_3_codec = Codec(dk.ATT_3, "double")
ATT_4_codec = Codec(dk.ATT_4, "double")
